/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Paneles.PMaestros;
import java.awt.BorderLayout;

/**
 *
 * @author TOULON-NOTE
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        butVentas = new javax.swing.JButton();
        butCompras = new javax.swing.JButton();
        butInformes = new javax.swing.JButton();
        butMaestros = new javax.swing.JButton();
        panelVisor = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema");
        setResizable(false);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setOpaque(false);

        butVentas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/r_ico_ventas_32_2.png"))); // NOI18N
        butVentas.setText("Ventas");
        butVentas.setBorderPainted(false);
        butVentas.setEnabled(false);
        butVentas.setFocusable(false);
        butVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butVentas.setMaximumSize(new java.awt.Dimension(69, 69));
        butVentas.setMinimumSize(new java.awt.Dimension(69, 69));
        butVentas.setPreferredSize(new java.awt.Dimension(69, 69));
        butVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(butVentas);

        butCompras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/r_ico_compras_32.png"))); // NOI18N
        butCompras.setText("Compras");
        butCompras.setBorderPainted(false);
        butCompras.setEnabled(false);
        butCompras.setFocusable(false);
        butCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butCompras.setMaximumSize(new java.awt.Dimension(69, 69));
        butCompras.setMinimumSize(new java.awt.Dimension(69, 69));
        butCompras.setPreferredSize(new java.awt.Dimension(69, 69));
        butCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(butCompras);

        butInformes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/r_ico_informes_32.png"))); // NOI18N
        butInformes.setText("Informes");
        butInformes.setBorderPainted(false);
        butInformes.setEnabled(false);
        butInformes.setFocusable(false);
        butInformes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butInformes.setMaximumSize(new java.awt.Dimension(69, 69));
        butInformes.setMinimumSize(new java.awt.Dimension(69, 69));
        butInformes.setPreferredSize(new java.awt.Dimension(69, 69));
        butInformes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(butInformes);

        butMaestros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butMaestros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/r_ico_maestros_32.png"))); // NOI18N
        butMaestros.setText("Maestros");
        butMaestros.setBorderPainted(false);
        butMaestros.setFocusable(false);
        butMaestros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butMaestros.setMaximumSize(new java.awt.Dimension(69, 69));
        butMaestros.setMinimumSize(new java.awt.Dimension(69, 69));
        butMaestros.setPreferredSize(new java.awt.Dimension(69, 69));
        butMaestros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        butMaestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMaestrosActionPerformed(evt);
            }
        });
        jToolBar1.add(butMaestros);

        jButton15.setText("jButton15");

        jButton16.setText("jButton16");

        jButton17.setText("jButton17");

        jButton18.setText("jButton18");

        javax.swing.GroupLayout panelVisorLayout = new javax.swing.GroupLayout(panelVisor);
        panelVisor.setLayout(panelVisorLayout);
        panelVisorLayout.setHorizontalGroup(
            panelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisorLayout.createSequentialGroup()
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton16))
            .addGroup(panelVisorLayout.createSequentialGroup()
                .addComponent(jButton18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton17))
        );
        panelVisorLayout.setVerticalGroup(
            panelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisorLayout.createSequentialGroup()
                .addGroup(panelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(jButton16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 582, Short.MAX_VALUE)
                .addGroup(panelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17)
                    .addComponent(jButton18)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(panelVisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelVisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butMaestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMaestrosActionPerformed
        // TODO add your handling code here:
        PMaestros PanelMaestros = new PMaestros();
        PanelMaestros.setVisible(true);
        PanelMaestros.setSize(1000, 631);
        PanelMaestros.setLocation(0, 0);
        
        panelVisor.removeAll();
        panelVisor.add(PanelMaestros, BorderLayout.CENTER);
        panelVisor.revalidate();
        panelVisor.repaint();
    }//GEN-LAST:event_butMaestrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCompras;
    private javax.swing.JButton butInformes;
    private javax.swing.JButton butMaestros;
    private javax.swing.JButton butVentas;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panelVisor;
    // End of variables declaration//GEN-END:variables
}
