/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Clases.CIVentaPack;
import Clases.CVerificar;
import ModelosTablas.MTIVentaPack;
import Objetos.OIVentaPack;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 *
 * @author TOULON-NOTE
 */
public class PInformeVentaPack extends javax.swing.JPanel {

    /**
     * Creates new form PInformeVentaPack
     */
    public PInformeVentaPack() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTitulo = new javax.swing.JLabel();
        jPanelBusqueda = new javax.swing.JPanel();
        labDesde = new javax.swing.JLabel();
        jDateChooserDesde = new com.toedter.calendar.JDateChooser("dd-MM-yyyy", "##/##/####", '_');
        jDateChooserHasta = new com.toedter.calendar.JDateChooser("dd-MM-yyyy", "##/##/####", '_');
        labHasta = new javax.swing.JLabel();
        butBuscar = new javax.swing.JButton();
        jToolBarMenu = new javax.swing.JToolBar();
        butExportarXLSX = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLista = new javax.swing.JTable();
        labTotalCantidad = new javax.swing.JLabel();
        labTotalValor = new javax.swing.JLabel();

        labTitulo.setBackground(new java.awt.Color(102, 102, 255));
        labTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTitulo.setText("Informe de Venta Pack");
        labTitulo.setOpaque(true);

        jPanelBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda"));

        labDesde.setText("Desde");

        labHasta.setText("Hasta");

        butBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/r_ico_buscar_32.png"))); // NOI18N
        butBuscar.setText("Buscar");
        butBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBusquedaLayout = new javax.swing.GroupLayout(jPanelBusqueda);
        jPanelBusqueda.setLayout(jPanelBusquedaLayout);
        jPanelBusquedaLayout.setHorizontalGroup(
            jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBusquedaLayout.createSequentialGroup()
                        .addGroup(jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labDesde))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labHasta))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelBusquedaLayout.setVerticalGroup(
            jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBusquedaLayout.createSequentialGroup()
                        .addGroup(jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labDesde)
                            .addComponent(labHasta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(butBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jToolBarMenu.setFloatable(false);
        jToolBarMenu.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBarMenu.setRollover(true);
        jToolBarMenu.setOpaque(false);

        butExportarXLSX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/r_ico_excel_32.png"))); // NOI18N
        butExportarXLSX.setText("Exportar");
        butExportarXLSX.setToolTipText("Agregar un Nuevo Usuario");
        butExportarXLSX.setFocusable(false);
        butExportarXLSX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butExportarXLSX.setMaximumSize(new java.awt.Dimension(69, 69));
        butExportarXLSX.setMinimumSize(new java.awt.Dimension(69, 69));
        butExportarXLSX.setPreferredSize(new java.awt.Dimension(69, 69));
        butExportarXLSX.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        butExportarXLSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExportarXLSXActionPerformed(evt);
            }
        });
        jToolBarMenu.add(butExportarXLSX);

        jTableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Pack", "Cantidad", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLista.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableLista.setRowHeight(30);
        jTableLista.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTableListaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTableLista);
        if (jTableLista.getColumnModel().getColumnCount() > 0) {
            jTableLista.getColumnModel().getColumn(0).setResizable(false);
            jTableLista.getColumnModel().getColumn(0).setPreferredWidth(374);
            jTableLista.getColumnModel().getColumn(1).setResizable(false);
            jTableLista.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTableLista.getColumnModel().getColumn(2).setResizable(false);
            jTableLista.getColumnModel().getColumn(2).setPreferredWidth(250);
        }

        labTotalCantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labTotalCantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labTotalCantidad.setText("Total Cantidad $0");

        labTotalValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labTotalValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labTotalValor.setText("Total Valor $0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labTotalCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(labTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labTotalCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscarActionPerformed
        // TODO add your handling code here:
        CIVentaPack IVentaPack = new CIVentaPack();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dateInicio = sdf.format(jDateChooserDesde.getDate());
        String dateFinal = sdf.format(jDateChooserHasta.getDate());
        jTableLista.setModel(new MTIVentaPack(IVentaPack.Listar(dateInicio, dateFinal)));
        jTableLista.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableLista.setRowHeight(30);
        jScrollPane1.setViewportView(jTableLista);
        if (jTableLista.getColumnModel().getColumnCount() > 0) {
            jTableLista.getColumnModel().getColumn(0).setResizable(false);
            jTableLista.getColumnModel().getColumn(0).setPreferredWidth(374);
            jTableLista.getColumnModel().getColumn(1).setResizable(false);
            jTableLista.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTableLista.getColumnModel().getColumn(2).setResizable(false);
            jTableLista.getColumnModel().getColumn(2).setPreferredWidth(250);
        }
        int cantTotal = 0;
        int valorTotal = 0;
        List<OIVentaPack> lista = ((MTIVentaPack)jTableLista.getModel()).getIVentaPack();
        
        for(OIVentaPack item : lista){
            cantTotal = cantTotal + item.getCantidad();
            valorTotal = valorTotal + item.getValor();
        }
        labTotalCantidad.setText(String.format("Total Cantidad $%s", cantTotal));
        labTotalValor.setText(String.format("Total Valor $%s", valorTotal));
    }//GEN-LAST:event_butBuscarActionPerformed

    private void jTableListaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTableListaAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTableListaAncestorAdded

    private void butExportarXLSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExportarXLSXActionPerformed
        // TODO add your handling code here:
        Imprimir();
    }//GEN-LAST:event_butExportarXLSXActionPerformed

    private void Imprimir(){
        CVerificar impri = new CVerificar();
        impri.Imprimir(jTableLista, labTitulo.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBuscar;
    private javax.swing.JButton butExportarXLSX;
    private com.toedter.calendar.JDateChooser jDateChooserDesde;
    private com.toedter.calendar.JDateChooser jDateChooserHasta;
    private javax.swing.JPanel jPanelBusqueda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLista;
    private javax.swing.JToolBar jToolBarMenu;
    private javax.swing.JLabel labDesde;
    private javax.swing.JLabel labHasta;
    private javax.swing.JLabel labTitulo;
    private javax.swing.JLabel labTotalCantidad;
    private javax.swing.JLabel labTotalValor;
    // End of variables declaration//GEN-END:variables
}
