/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Clases.CCliente;
import Clases.CComuna;
import Clases.CPack;
import Clases.CVenta;
import Clases.CVerificar;
import Dialogos.DCrudCliente;
import Dialogos.DCrudPack;
import Objetos.OAnimacion;
import Dialogos.DError;
import Dialogos.DPregunta;
import ModeloCombox.MCComuna;
import ModelosTablas.MTVentaPackDeta;
import ModelosTablas.MTVentaSelecPack;
import Objetos.OBanco;
import Objetos.OCliente;
import Objetos.OError;
import Objetos.OEstadoVenta;
import Objetos.OVenta;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author TOULON-NOTE
 */
public class PVenta extends javax.swing.JPanel {

    private OVenta Venta = new OVenta();
    private OAnimacion AnimacionRut = null;

    /**
     * Creates new form PVenta
     */
    public PVenta() {
        initComponents();
        LlenarComboComuna();
        setJTexFieldChanged(txtRut);
        setJTexFieldChanged2(txtCantidad);
        ListarArticulos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTitulo = new javax.swing.JLabel();
        jPanelDCS = new javax.swing.JPanel();
        labNumeroPedido = new javax.swing.JLabel();
        txtNumeroPedido = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        labRut = new javax.swing.JLabel();
        butBuscar = new javax.swing.JButton();
        labNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        labEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        labTelefono = new javax.swing.JLabel();
        butLimpiarDCS = new javax.swing.JButton();
        jPanelDD = new javax.swing.JPanel();
        labNombreDestinatario = new javax.swing.JLabel();
        txtNombreDestinatario = new javax.swing.JTextField();
        labFechaEntrega = new javax.swing.JLabel();
        jComboBoxComuna = new javax.swing.JComboBox<>();
        labComuna = new javax.swing.JLabel();
        labDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtHoraInicio = new javax.swing.JTextField();
        labHoraFin = new javax.swing.JLabel();
        txtHoraFin = new javax.swing.JTextField();
        labHoraInicio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSaludo = new javax.swing.JTextArea();
        labSaludo = new javax.swing.JLabel();
        butLimpiarDD = new javax.swing.JButton();
        jDateChooserFE = new com.toedter.calendar.JDateChooser("dd-MM-yyyy", "##/##/####", '_');
        txtApellidoDestinatario = new javax.swing.JTextField();
        labApellidoDestinatario = new javax.swing.JLabel();
        txtTelefonoDestinatario = new javax.swing.JTextField();
        labTelefonoDestinatario = new javax.swing.JLabel();
        jPanelPS = new javax.swing.JPanel();
        labCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombrePack = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        labNombrePack = new javax.swing.JLabel();
        labCantidad = new javax.swing.JLabel();
        labPrecio = new javax.swing.JLabel();
        jToolBarMenu = new javax.swing.JToolBar();
        butCancelar = new javax.swing.JButton();
        butGuardar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDetallePack = new javax.swing.JTable();
        labDetallePack = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        labTotal = new javax.swing.JLabel();
        jPanelSDP = new javax.swing.JPanel();
        labBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListaBuscar = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        labTitulo.setBackground(new java.awt.Color(102, 102, 255));
        labTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTitulo.setText("Venta");
        labTitulo.setOpaque(true);

        jPanelDCS.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Cliente Solicitante"));

        labNumeroPedido.setText("Numero Pedido");

        txtNumeroPedido.setEditable(false);
        txtNumeroPedido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtRut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRutKeyReleased(evt);
            }
        });

        labRut.setText("Rut");

        butBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/r_ico_buscar_24.png"))); // NOI18N
        butBuscar.setToolTipText("Buscar Cliente");
        butBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        butBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscarActionPerformed(evt);
            }
        });

        labNombreCliente.setText("Nombre Cliente");

        txtNombreCliente.setEditable(false);

        labEmail.setText("Email");

        txtEmail.setEditable(false);

        txtTelefono.setEditable(false);

        labTelefono.setText("Telefono");

        butLimpiarDCS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/r_ico_limpio_24.png"))); // NOI18N
        butLimpiarDCS.setToolTipText("Limpiar Datos Cliente Solicitante");
        butLimpiarDCS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        butLimpiarDCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLimpiarDCSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDCSLayout = new javax.swing.GroupLayout(jPanelDCS);
        jPanelDCS.setLayout(jPanelDCSLayout);
        jPanelDCSLayout.setHorizontalGroup(
            jPanelDCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDCSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDCSLayout.createSequentialGroup()
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butLimpiarDCS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDCSLayout.createSequentialGroup()
                        .addGroup(jPanelDCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDCSLayout.createSequentialGroup()
                                .addGroup(jPanelDCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labNumeroPedido))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labRut)
                                    .addGroup(jPanelDCSLayout.createSequentialGroup()
                                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(butBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(labEmail)
                            .addGroup(jPanelDCSLayout.createSequentialGroup()
                                .addGroup(jPanelDCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labNombreCliente))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labTelefono)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDCSLayout.setVerticalGroup(
            jPanelDCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDCSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNumeroPedido)
                    .addComponent(labRut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNombreCliente)
                    .addComponent(labTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDCSLayout.createSequentialGroup()
                        .addComponent(labEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(butLimpiarDCS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDD.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Destinatario"));

        labNombreDestinatario.setText("Nombre Destinatario");

        labFechaEntrega.setText("Fecha Entrega");

        jComboBoxComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labComuna.setText("Comuna");

        labDireccion.setText("Direccion");

        txtHoraInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labHoraFin.setText("H. F. Entrega");

        txtHoraFin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labHoraInicio.setText("H. I. Entrega");

        txtSaludo.setColumns(20);
        txtSaludo.setLineWrap(true);
        txtSaludo.setRows(4);
        jScrollPane1.setViewportView(txtSaludo);

        labSaludo.setText("Saludo");

        butLimpiarDD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/r_ico_limpio_24.png"))); // NOI18N
        butLimpiarDD.setToolTipText("Limpiar Datos Destinatario");
        butLimpiarDD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        butLimpiarDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLimpiarDDActionPerformed(evt);
            }
        });

        labApellidoDestinatario.setText("Apellido Destinatario");

        labTelefonoDestinatario.setText("Telefono");

        javax.swing.GroupLayout jPanelDDLayout = new javax.swing.GroupLayout(jPanelDD);
        jPanelDD.setLayout(jPanelDDLayout);
        jPanelDDLayout.setHorizontalGroup(
            jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDDLayout.createSequentialGroup()
                        .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labFechaEntrega)
                            .addComponent(jDateChooserFE, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labComuna)
                            .addComponent(jComboBoxComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDDLayout.createSequentialGroup()
                                .addComponent(txtTelefonoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtHoraFin))
                            .addGroup(jPanelDDLayout.createSequentialGroup()
                                .addComponent(labTelefonoDestinatario)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanelDDLayout.createSequentialGroup()
                        .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labDireccion)
                            .addComponent(butLimpiarDD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDDLayout.createSequentialGroup()
                                .addComponent(labSaludo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDDLayout.createSequentialGroup()
                        .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDDLayout.createSequentialGroup()
                                .addComponent(labNombreDestinatario)
                                .addGap(81, 81, 81))
                            .addComponent(txtNombreDestinatario))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoDestinatario)
                            .addGroup(jPanelDDLayout.createSequentialGroup()
                                .addComponent(labApellidoDestinatario)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labHoraFin)
                            .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labHoraInicio))))
                .addContainerGap())
        );
        jPanelDDLayout.setVerticalGroup(
            jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNombreDestinatario)
                    .addComponent(labApellidoDestinatario)
                    .addComponent(labHoraInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labFechaEntrega)
                    .addComponent(labComuna)
                    .addComponent(labHoraFin)
                    .addComponent(labTelefonoDestinatario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelefonoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserFE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDireccion)
                    .addComponent(labSaludo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDDLayout.createSequentialGroup()
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 32, Short.MAX_VALUE)
                        .addComponent(butLimpiarDD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelPS.setBorder(javax.swing.BorderFactory.createTitledBorder("Pack Seleccionado"));

        labCodigo.setText("Codigo");

        txtCodigo.setEditable(false);

        txtNombrePack.setEditable(false);

        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPrecio.setEditable(false);

        labNombrePack.setText("Nombre Pack");

        labCantidad.setText("Cant.");

        labPrecio.setText("Precio");

        jToolBarMenu.setFloatable(false);
        jToolBarMenu.setRollover(true);
        jToolBarMenu.setBorderPainted(false);
        jToolBarMenu.setOpaque(false);

        butCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/r_ico_cancelar_32.png"))); // NOI18N
        butCancelar.setText("Cancelar");
        butCancelar.setToolTipText("Cancelar");
        butCancelar.setFocusable(false);
        butCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butCancelar.setMaximumSize(new java.awt.Dimension(69, 69));
        butCancelar.setMinimumSize(new java.awt.Dimension(69, 69));
        butCancelar.setPreferredSize(new java.awt.Dimension(69, 69));
        butCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMenu.add(butCancelar);

        butGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/r_ico_guardar_32.png"))); // NOI18N
        butGuardar.setText("Guardar");
        butGuardar.setToolTipText("Guardar");
        butGuardar.setFocusable(false);
        butGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butGuardar.setMaximumSize(new java.awt.Dimension(69, 69));
        butGuardar.setMinimumSize(new java.awt.Dimension(69, 69));
        butGuardar.setPreferredSize(new java.awt.Dimension(69, 69));
        butGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        butGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGuardarActionPerformed(evt);
            }
        });
        jToolBarMenu.add(butGuardar);

        jTableDetallePack.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cant.", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDetallePack.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableDetallePack.setRowHeight(30);
        jScrollPane4.setViewportView(jTableDetallePack);
        if (jTableDetallePack.getColumnModel().getColumnCount() > 0) {
            jTableDetallePack.getColumnModel().getColumn(0).setResizable(false);
            jTableDetallePack.getColumnModel().getColumn(0).setPreferredWidth(55);
            jTableDetallePack.getColumnModel().getColumn(1).setResizable(false);
            jTableDetallePack.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        labDetallePack.setText("Detalle del Pack");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setText("$0");

        labTotal.setText("Total");

        javax.swing.GroupLayout jPanelPSLayout = new javax.swing.GroupLayout(jPanelPS);
        jPanelPS.setLayout(jPanelPSLayout);
        jPanelPSLayout.setHorizontalGroup(
            jPanelPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPSLayout.createSequentialGroup()
                        .addGroup(jPanelPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombrePack, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labNombrePack))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPSLayout.createSequentialGroup()
                                .addComponent(labPrecio)
                                .addGap(0, 70, Short.MAX_VALUE))
                            .addComponent(txtPrecio)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPSLayout.createSequentialGroup()
                        .addGroup(jPanelPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanelPSLayout.createSequentialGroup()
                                .addComponent(labDetallePack)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labTotal)
                            .addGroup(jPanelPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jToolBarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTotal)))))
                .addContainerGap())
        );
        jPanelPSLayout.setVerticalGroup(
            jPanelPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCodigo)
                    .addComponent(labNombrePack)
                    .addComponent(labCantidad)
                    .addComponent(labPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtCantidad)
                    .addComponent(txtNombrePack)
                    .addComponent(txtCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDetallePack)
                    .addComponent(labTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPSLayout.createSequentialGroup()
                        .addComponent(txtTotal)
                        .addGap(18, 18, 18)
                        .addComponent(jToolBarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelSDP.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccion del Pack"));

        labBuscar.setText("Buscar (Codigo/Nombre)");

        jTableListaBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaBuscar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableListaBuscar.setRowHeight(30);
        jTableListaBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaBuscarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableListaBuscar);
        if (jTableListaBuscar.getColumnModel().getColumnCount() > 0) {
            jTableListaBuscar.getColumnModel().getColumn(0).setResizable(false);
            jTableListaBuscar.getColumnModel().getColumn(0).setPreferredWidth(97);
            jTableListaBuscar.getColumnModel().getColumn(1).setResizable(false);
            jTableListaBuscar.getColumnModel().getColumn(1).setPreferredWidth(237);
            jTableListaBuscar.getColumnModel().getColumn(2).setResizable(false);
            jTableListaBuscar.getColumnModel().getColumn(2).setPreferredWidth(80);
        }

        jButton1.setText("Prueba");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSDPLayout = new javax.swing.GroupLayout(jPanelSDP);
        jPanelSDP.setLayout(jPanelSDPLayout);
        jPanelSDPLayout.setHorizontalGroup(
            jPanelSDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSDPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar)
                    .addGroup(jPanelSDPLayout.createSequentialGroup()
                        .addComponent(labBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSDPLayout.setVerticalGroup(
            jPanelSDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSDPLayout.createSequentialGroup()
                .addGroup(jPanelSDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSDPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labBuscar))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDCS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDCS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butLimpiarDCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLimpiarDCSActionPerformed
        // TODO add your handling code here:
        LimpiarDatosClienteSolicitante();
    }//GEN-LAST:event_butLimpiarDCSActionPerformed

    private void butLimpiarDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLimpiarDDActionPerformed
        // TODO add your handling code here:
        txtNombreDestinatario.setText("");
        txtApellidoDestinatario.setText("");
        txtTelefonoDestinatario.setText("");
        txtHoraInicio.setText("");
        jDateChooserFE.setCalendar(null);
        LlenarComboComuna();
        txtHoraFin.setText("");
        txtDireccion.setText("");
        txtSaludo.setText("");
    }//GEN-LAST:event_butLimpiarDDActionPerformed

    private void butBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscarActionPerformed
        // TODO add your handling code here:
        //boolean Validacion = true;
        if (!txtRut.getText().trim().isEmpty()) {
            OError Error = new CVerificar(txtRut.getText()).Validar();
            if (Error.isConfirma()) {
                CCliente Cliente = new CCliente();
                Cliente.setRut(txtRut.getText().trim());
                Error = Cliente.BuscaRut();
                if (Error.isConfirma()) {
                    OCliente ocliente = (OCliente) Error.getRetorno();
                    txtNombreCliente.setText(String.format("%s %s", ocliente.getNombre(), ocliente.getApellido()));
                    txtTelefono.setText(String.valueOf(ocliente.getTelefono()));
                    txtEmail.setText(ocliente.getCorreo());
                    Venta.setCliente(ocliente);
                } else {
                    if (Error.getMensaje().equals("Cliente Existe y esta Desactivado. Desea Activarlo?")) {
                        DPregunta Mensaje = new DPregunta(new javax.swing.JDialog(), true, this);
                        Mensaje.labMensaje.setText(Error.getMensaje());
                        Mensaje.setVisible(true);
                    } else if (Error.getMensaje().equals("Cliente NO Existe. Desea Agregarlo?")) {
                        DPregunta Mensaje = new DPregunta(new javax.swing.JDialog(), true, this);
                        Mensaje.labMensaje.setText(Error.getMensaje());
                        Mensaje.setVisible(true);
                    } else {
                        DError Mensaje = new DError(new javax.swing.JDialog(), true);
                        Mensaje.labMensaje.setText(Error.getMensaje());
                        Mensaje.setVisible(true);
                    }
                }
            } else {
                DError Mensaje = new DError(new javax.swing.JDialog(), true);
                Mensaje.labMensaje.setText(Error.getMensaje());
                Mensaje.setVisible(true);
            }
        } else {
            if (AnimacionRut == null) {
                AnimacionRut = new OAnimacion(txtRut);
                AnimacionRut.EjecutarTxt();
                txtRut.setToolTipText("El Rut es Obligatorio");
            }
        }
    }//GEN-LAST:event_butBuscarActionPerformed

    private void txtRutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyReleased
        // TODO add your handling code here:
        if (AnimacionRut != null) {
            if (txtRut.getText().trim().isEmpty()) {
                return;
            }
            AnimacionRut.DetenerTxt();
            AnimacionRut = null;
            txtRut.setToolTipText(null);
        }
    }//GEN-LAST:event_txtRutKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DCrudPack CrudArticulo = new DCrudPack(new javax.swing.JDialog(), true);
        CrudArticulo.setTitle("Agregar Articulo");
        //CrudUsuario.txtRut.setText(txtRut.getText());
        CrudArticulo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableListaBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaBuscarMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            //butEditar.setEnabled(true);
            //butDesactivar.setEnabled(true);

            //RowIdSeleccionado = jTableTabla.rowAtPoint(evt.getPoint());
            //String uno = jTableTabla.getValueAt(RowIdSeleccionado, 0).toString();
            MTVentaSelecPack selecpack = (MTVentaSelecPack) jTableListaBuscar.getModel();
            selecpack.getPacks().get(jTableListaBuscar.getSelectedRow()).getId();
            Venta.setPack(selecpack.getPacks().get(jTableListaBuscar.getSelectedRow()));
            txtCodigo.setText(String.valueOf(selecpack.getPacks().get(jTableListaBuscar.getSelectedRow()).getId()));
            txtNombrePack.setText(selecpack.getPacks().get(jTableListaBuscar.getSelectedRow()).getNombre());
            txtCantidad.setText(String.valueOf(1));
            txtPrecio.setText(String.valueOf(selecpack.getPacks().get(jTableListaBuscar.getSelectedRow()).getCosto()));
            jTableDetallePack.setModel(new MTVentaPackDeta(selecpack.getPacks().get(jTableListaBuscar.getSelectedRow()).getArticulos()));
            jTableDetallePack.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            jTableDetallePack.setRowHeight(30);
            jScrollPane4.setViewportView(jTableDetallePack);
            if (jTableDetallePack.getColumnModel().getColumnCount() > 0) {
                jTableDetallePack.getColumnModel().getColumn(0).setResizable(false);
                jTableDetallePack.getColumnModel().getColumn(0).setPreferredWidth(55);
                jTableDetallePack.getColumnModel().getColumn(1).setResizable(false);
                jTableDetallePack.getColumnModel().getColumn(1).setPreferredWidth(200);
            }
            Venta.setCantidad(1);
            //System.out.println(String.valueOf(dos.getUsuarios().get(RowIdSeleccionado).getId()));
            if (evt.getClickCount() == 2) {
                System.out.println("2 Click");
            }
        }
    }//GEN-LAST:event_jTableListaBuscarMouseClicked

    private void butGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGuardarActionPerformed
        // TODO add your handling code here:
        //int id, int total, String fechaVenta, String fechaTrasferencia, int codigoTrasferencia, String nombreDestinatario, 
        //String apellidoDestinatario, String direccionDestinatario, int telefonoDestinatario, String fechaEntrega, String horaEntregaInicial, 
        //String horaEntregaFinal, String saludoTexto, int cantidad, OCliente cliente, OPack pack, OBanco banco, OComuna comuna
        //, OEstadoVenta estadoVenta
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(new Date());
        String date2 = sdf.format(jDateChooserFE.getDate());
        CVenta Ven = new CVenta(0, Venta.getTotalT(), date, "", 0, txtNombreDestinatario.getText().trim(), txtApellidoDestinatario.getText().trim()
                , txtDireccion.getText().trim(), Integer.valueOf(txtTelefonoDestinatario.getText().trim()), date2
                , txtHoraInicio.getText().trim(), txtHoraFin.getText().trim(), txtSaludo.getText().trim(), Venta.getCantidad(), Venta.getCliente()
                , Venta.getPack(), new OBanco(), ((MCComuna)jComboBoxComuna.getModel()).getComunas().get(jComboBoxComuna.getSelectedIndex())
                , new OEstadoVenta());
                
    }//GEN-LAST:event_butGuardarActionPerformed

    private void ListarArticulos() {
        MTVentaSelecPack articulosmt = new MTVentaSelecPack(new CPack().Listar());
        jTableListaBuscar.setModel(articulosmt);
        jTableListaBuscar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableListaBuscar.setRowHeight(30);
        jScrollPane2.setViewportView(jTableListaBuscar);
        if (jTableListaBuscar.getColumnModel().getColumnCount() > 0) {
            jTableListaBuscar.getColumnModel().getColumn(0).setResizable(false);
            jTableListaBuscar.getColumnModel().getColumn(0).setPreferredWidth(97);
            jTableListaBuscar.getColumnModel().getColumn(1).setResizable(false);
            jTableListaBuscar.getColumnModel().getColumn(1).setPreferredWidth(237);
            jTableListaBuscar.getColumnModel().getColumn(2).setResizable(false);
            jTableListaBuscar.getColumnModel().getColumn(2).setPreferredWidth(80);
        }
    }

    private void LlenarComboComuna() {
        jComboBoxComuna.setModel(new MCComuna(new CComuna().Listar("Activos")));
    }

    public void LimpiarDatosClienteSolicitante() {
        //txtNumeroPedido.setText("");
        txtRut.setText("");
        txtNombreCliente.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
        Venta.setCliente(new OCliente());
    }

    public void AgregarCliente() {
        DCrudCliente CrudUsuario = new DCrudCliente(new javax.swing.JDialog(), true);
        CrudUsuario.setTitle("Agregar Cliente");
        CrudUsuario.txtRut.setText(txtRut.getText());
        CrudUsuario.setVisible(true);
    }

    public void setJTexFieldChanged(javax.swing.JTextField textField) {
        DocumentListener documentListener = new DocumentListener() {

            @Override
            public void changedUpdate(DocumentEvent documentEvent) {
                printIt(documentEvent);
            }

            @Override
            public void insertUpdate(DocumentEvent documentEvent) {
                printIt(documentEvent);
            }

            @Override
            public void removeUpdate(DocumentEvent documentEvent) {
                printIt(documentEvent);
            }
        };
        textField.getDocument().addDocumentListener(documentListener);
    }

    private void printIt(DocumentEvent documentEvent) {
        DocumentEvent.EventType type = documentEvent.getType();

        if (type.equals(DocumentEvent.EventType.CHANGE)) {
            System.out.println("CHANGE:" + txtRut.getText());
        } else if (type.equals(DocumentEvent.EventType.INSERT)) {
            //txtEjemploJTextFieldChanged();
            System.out.println("INSERT:" + txtRut.getText());
            //if(AnimacionRut == null){
            //    AnimacionRut = new OAnimacion(txtRut);
            //    AnimacionRut.EjecutarTxt();
            //    txtRut.setToolTipText("El Rut es Invalido");
            //}
            if (!txtRut.getText().trim().isEmpty()) {
                OError Error = new CVerificar(txtRut.getText()).Validar();
                if (Error.isConfirma()) {
                    txtRut.setBackground(Color.green);
                    txtRut.setToolTipText(Error.getMensaje());
                } else {
                    txtRut.setBackground(Color.red);
                    txtRut.setToolTipText(Error.getMensaje());
                }
            } else {
                txtRut.setBackground(Color.WHITE);
                txtRut.setToolTipText(null);
            }
        } else if (type.equals(DocumentEvent.EventType.REMOVE)) {
            //txtEjemploJTextFieldChanged();
            System.out.println("REMOVE:" + txtRut.getText());
            //if(AnimacionRut == null){
            //    AnimacionRut = new OAnimacion(txtRut);
            //    AnimacionRut.EjecutarTxt();
            //    txtRut.setToolTipText("El Rut es Invalido");
            //}
            if (!txtRut.getText().trim().isEmpty()) {
                OError Error = new CVerificar(txtRut.getText()).Validar();
                if (Error.isConfirma()) {
                    txtRut.setBackground(Color.green);
                    txtRut.setToolTipText(Error.getMensaje());
                } else {
                    txtRut.setBackground(Color.red);
                    txtRut.setToolTipText(Error.getMensaje());
                }
            } else {
                txtRut.setBackground(Color.WHITE);
                txtRut.setToolTipText(null);
            }
        }
    }

    public void setJTexFieldChanged2(javax.swing.JTextField textField) {
        DocumentListener documentListener = new DocumentListener() {

            @Override
            public void changedUpdate(DocumentEvent documentEvent) {
                printIt2(documentEvent);
            }

            @Override
            public void insertUpdate(DocumentEvent documentEvent) {
                printIt2(documentEvent);
            }

            @Override
            public void removeUpdate(DocumentEvent documentEvent) {
                printIt2(documentEvent);
            }
        };
        textField.getDocument().addDocumentListener(documentListener);
    }

    private void printIt2(DocumentEvent documentEvent) {
        DocumentEvent.EventType type = documentEvent.getType();

        if (type.equals(DocumentEvent.EventType.CHANGE)) {
            System.out.println("CHANGE:" + txtCantidad.getText());
        } else if (type.equals(DocumentEvent.EventType.INSERT)) {
            System.out.println("INSERT:" + txtCantidad.getText());
            if (!txtCantidad.getText().trim().isEmpty()) {
                int cant = Integer.parseInt(txtCantidad.getText().trim());
                Venta.setCantidad(cant);
                txtTotal.setText(String.format("$ %s", String.valueOf(Venta.getTotalT())));
            } else {
                txtTotal.setText("$0");
            }
        } else if (type.equals(DocumentEvent.EventType.REMOVE)) {
            System.out.println("REMOVE:" + txtCantidad.getText());
            if (!txtCantidad.getText().trim().isEmpty()) {
                int cant = Integer.parseInt(txtCantidad.getText().trim());
                Venta.setCantidad(cant);
                txtTotal.setText(String.format("$ %s", String.valueOf(Venta.getTotalT())));
            } else {
                txtTotal.setText("$0");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBuscar;
    private javax.swing.JButton butCancelar;
    private javax.swing.JButton butGuardar;
    private javax.swing.JButton butLimpiarDCS;
    private javax.swing.JButton butLimpiarDD;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxComuna;
    private com.toedter.calendar.JDateChooser jDateChooserFE;
    private javax.swing.JPanel jPanelDCS;
    private javax.swing.JPanel jPanelDD;
    private javax.swing.JPanel jPanelPS;
    private javax.swing.JPanel jPanelSDP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableDetallePack;
    private javax.swing.JTable jTableListaBuscar;
    private javax.swing.JToolBar jToolBarMenu;
    private javax.swing.JLabel labApellidoDestinatario;
    private javax.swing.JLabel labBuscar;
    private javax.swing.JLabel labCantidad;
    private javax.swing.JLabel labCodigo;
    private javax.swing.JLabel labComuna;
    private javax.swing.JLabel labDetallePack;
    private javax.swing.JLabel labDireccion;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labFechaEntrega;
    private javax.swing.JLabel labHoraFin;
    private javax.swing.JLabel labHoraInicio;
    private javax.swing.JLabel labNombreCliente;
    private javax.swing.JLabel labNombreDestinatario;
    private javax.swing.JLabel labNombrePack;
    private javax.swing.JLabel labNumeroPedido;
    private javax.swing.JLabel labPrecio;
    private javax.swing.JLabel labRut;
    private javax.swing.JLabel labSaludo;
    private javax.swing.JLabel labTelefono;
    private javax.swing.JLabel labTelefonoDestinatario;
    private javax.swing.JLabel labTitulo;
    private javax.swing.JLabel labTotal;
    private javax.swing.JTextField txtApellidoDestinatario;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoraFin;
    private javax.swing.JTextField txtHoraInicio;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreDestinatario;
    private javax.swing.JTextField txtNombrePack;
    private javax.swing.JTextField txtNumeroPedido;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextArea txtSaludo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoDestinatario;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
